version: '3.8'
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-80}:80"
    networks:
      - postgres
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tribal
      POSTGRES_PASSWORD: Tribal22
      POSTGRES_DB: tribal_market

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight
    restart: always
    links:
      - redis
    ports:
      - 82:8001

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  s3data:
  s3metadata:

