version: '3.8'
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - 8005:80
    networks:
      - app-tier
    restart: always

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_developer
      POSTGRES_PASSWORD: admin_developer_password
      POSTGRES_DB: sach_giam_gia

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  # redisinsight:
  #   image: redislabs/redisinsight
  #   restart: always
  #   links:
  #     - redis
  #   ports:
  #     - 82:8001

  minio:
    image: minio/minio
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: minio_developer_user
      MINIO_ROOT_PASSWORD: minio_developer_password
    command: server --console-address ":9001" /data

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
  pgadmin:
